; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Mar 23 2025 15:32:50 GMT-0500 (Central Daylight Time)
; ================================================================================

DATAGKI0HYDQBXP:
	dc.w DATAGKI0HYDQBXP_0-DATAGKI0HYDQBXP, DATAGKI0HYDQBXP_1-DATAGKI0HYDQBXP
	dc.w DATAGKI0HYDQBXP_2-DATAGKI0HYDQBXP, DATAGKI0HYDQBXP_3-DATAGKI0HYDQBXP
	dc.w DATAGKI0HYDQBXP_4-DATAGKI0HYDQBXP, DATAGKI0HYDQBXP_5-DATAGKI0HYDQBXP
	dc.w DATAGKI0HYDQBXP_6-DATAGKI0HYDQBXP, DATAGKI0HYDQBXP_7-DATAGKI0HYDQBXP
DATAGKI0HYDQBXP_0: dc.b $8
	dc.b $C, $F, $1, $26, $8
	dc.b $2C, $F, $1, $36, $8
	dc.b $4C, $D, $1, $46, $8
	dc.b $4, $8, $1, $4E, $20
	dc.b $C, $B, $1, $51, $28
	dc.b $2C, $B, $1, $5D, $28
	dc.b $4C, $5, $1, $69, $28
	dc.b $14, $7, $1, $6D, $40
DATAGKI0HYDQBXP_1: dc.b $B
	dc.b $6, $F, $1, $75, $1
	dc.b $6, $F, $1, $85, $21
	dc.b $6, $7, $1, $95, $41
	dc.b $26, $F, $1, $9D, $1
	dc.b $26, $F, $1, $AD, $21
	dc.b $26, $7, $1, $BD, $41
	dc.b $46, $C, $1, $C5, $1
	dc.b $46, $E, $1, $C9, $21
	dc.b $46, $6, $1, $D5, $41
	dc.b $4E, $8, $1, $DB, $9
	dc.b $56, $4, $1, $DE, $11
DATAGKI0HYDQBXP_2: dc.b $B
	dc.b $F2, $F, $1, $75, $1
	dc.b $F2, $F, $1, $85, $21
	dc.b $F2, $7, $1, $95, $41
	dc.b $12, $F, $1, $9D, $1
	dc.b $12, $F, $1, $AD, $21
	dc.b $12, $7, $1, $BD, $41
	dc.b $32, $C, $1, $C5, $1
	dc.b $32, $E, $1, $C9, $21
	dc.b $32, $6, $1, $D5, $41
	dc.b $3A, $8, $1, $DB, $9
	dc.b $42, $4, $1, $DE, $11
DATAGKI0HYDQBXP_3: dc.b $A
	dc.b $FC, $F, $0, $0, $8
	dc.b $F4, $8, $0, $10, $28
	dc.b $FC, $F, $0, $13, $28
	dc.b $4, $0, $0, $23, $48
	dc.b $C, $6, $0, $24, $48
	dc.b $24, $0, $0, $2A, $48
	dc.b $1C, $D, $0, $2B, $8
	dc.b $1C, $E, $0, $33, $28
	dc.b $2C, $B, $0, $3F, $10
	dc.b $34, $8, $0, $4B, $28
DATAGKI0HYDQBXP_4: dc.b $10
	dc.b $F8, $F, $1, $E0, $9
	dc.b $F8, $7, $1, $F0, $29
	dc.b $0, $3, $1, $F8, $1
	dc.b $0, $3, $1, $FC, $39
	dc.b $10, $1, $2, $0, $F9
	dc.b $18, $D, $2, $2, $9
	dc.b $18, $7, $2, $A, $29
	dc.b $18, $3, $2, $12, $41
	dc.b $20, $1, $2, $16, $1
	dc.b $20, $3, $2, $18, $39
	dc.b $28, $8, $2, $1C, $11
	dc.b $30, $7, $2, $1F, $19
	dc.b $38, $1, $2, $27, $11
	dc.b $38, $6, $2, $29, $29
	dc.b $38, $1, $2, $2F, $41
	dc.b $40, $1, $2, $31, $39
DATAGKI0HYDQBXP_5: dc.b $B
	dc.b $2C, $F, $0, $6E, $E2
	dc.b $EC, $F, $0, $7E, $2
	dc.b $C, $F, $0, $8E, $2
	dc.b $2C, $F, $0, $9E, $2
	dc.b $EC, $F, $0, $AE, $22
	dc.b $C, $F, $0, $BE, $22
	dc.b $2C, $F, $0, $CE, $22
	dc.b $EC, $F, $0, $DE, $42
	dc.b $C, $F, $0, $EE, $42
	dc.b $2C, $F, $0, $FE, $42
	dc.b $C, $7, $1, $16, $62
DATAGKI0HYDQBXP_6: dc.b $F
	dc.b $EC, $F, $0, $4E, $E2
	dc.b $C, $F, $0, $5E, $E2
	dc.b $2C, $F, $0, $6E, $E2
	dc.b $EC, $F, $0, $7E, $2
	dc.b $C, $F, $0, $8E, $2
	dc.b $2C, $F, $0, $9E, $2
	dc.b $EC, $F, $0, $AE, $22
	dc.b $C, $F, $0, $BE, $22
	dc.b $2C, $F, $0, $CE, $22
	dc.b $EC, $F, $0, $DE, $42
	dc.b $C, $F, $0, $EE, $42
	dc.b $2C, $F, $0, $FE, $42
	dc.b $EC, $7, $1, $E, $62
	dc.b $C, $7, $1, $16, $62
	dc.b $2C, $7, $1, $1E, $62
DATAGKI0HYDQBXP_7: dc.b $F
	dc.b $EC, $F, $2, $33, $E2
	dc.b $C, $F, $2, $43, $E2
	dc.b $2C, $F, $2, $53, $E2
	dc.b $EC, $F, $2, $63, $2
	dc.b $C, $F, $2, $73, $2
	dc.b $2C, $F, $2, $83, $2
	dc.b $EC, $F, $2, $93, $22
	dc.b $C, $F, $2, $A3, $22
	dc.b $2C, $F, $2, $B3, $22
	dc.b $EC, $F, $2, $C3, $42
	dc.b $C, $F, $2, $D3, $42
	dc.b $2C, $F, $2, $E3, $42
	dc.b $EC, $7, $2, $F3, $62
	dc.b $C, $7, $2, $FB, $62
	dc.b $2C, $7, $3, $3, $62
	even